[App]
Port=8899
Rule="rule.conf"
Token="helloworld"

[Common]
MixedPort=7890
AllowLan= false
Mode="rule"
LogLevel= "info"
ExternalController="127.0.0.1:9090"

[Common.Experimental]
IgnoreResolveFail=true



[[Subscribes]]
Name="Walless"
URL="xxxx"
IgnoreChars = ["菲律宾100倍扣流量","阿根廷"]
FilterChars=["{emoji}","{space}"]
Convert = false


[[Groups]]
Name = "手动切换"
Type = "select"
Proxies = ["DIRECT"]
AppendNodes = true


[[Groups]]
Name = "出国专用"
Type = "select"
Proxies = ["自动选择", "手动切换"]
AppendNodes = false
Rules = [
    "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt|",
    "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt|",
    "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt|",
    "IP-CIDR|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt|",
]

[[Groups]]
Name = "漏网之鱼"
Type = "select"
Proxies = ["直连", "自动选择", "手动切换"]
AppendNodes = false

[[Groups]]
Name = "应用净化"
Type = "select"
Proxies = ["REJECT", "DIRECT", "自动选择", "手动切换"]
AppendNodes = false
Rules = [
    "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt|",
]


[[Groups]]
Name = "直连"
Type = "select"
Proxies = ["DIRECT"]
AppendNodes = false
Rules = [
    # "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt|",
    # "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt|",
    # "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt|",
    # "DOMAIN|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt|",
    "IP-CIDR|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt|",
    "IP-CIDR|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt|",
    "|https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt|",
]

[[Groups]]
Name = "自动选择"
Type = "url-test"
Proxies = []
TestURL = "http://www.gstatic.com/generate_204"
Interval = 3600
AppendNodes = true
