[App]
Port=8899
TestURL="http://www.gstatic.com/generate_204"

[[Source]]
Name="Walless"
SubscribeURL="https://sub.wl-sub1.com/api/v1/client/subscribe?token=f6bf7db5bfe5e2bb3ca809c68ed1d3a0&flag=clash"
IgnoreNodes = ["菲律宾100倍扣流量"]
FilterChars=["{emoji}","{space}"]


[[Groups]]
Name="国外流量"
Type="select"
Proxies=[]
AppendNodes=true


[[Groups]]
Name="国外流量"
Type="url-test"
Proxies=[]
TestURL = "http://www.gstatic.com/generate_204"
AppendNodes=true
